export const Colors = {
  terracotta:      '#C1652D',
  terracottaLight: '#E8896A',
  terracottaFaint: '#FAF0EA',
  cream:           '#FAF7F2',
  stone:           '#78716C',
  stoneDark:       '#44403C',
  stoneLight:      '#A8A29E',
  border:          '#E7E5E4',
  green:           '#4A7C59',
  greenLight:      '#D1FAE5',
  gold:            '#D4A843',
  goldLight:       '#FEF3C7',
  red:             '#DC2626',
  redLight:        '#FEE2E2',
  blue:            '#2563EB',
  blueLight:       '#DBEAFE',
  white:           '#FFFFFF',
  black:           '#0C0A09',
  bgCard:          '#FFFFFF',
  bgScreen:        '#FAF7F2',
}
